version: 2 # will always be v2 of circle ci
jobs:
  build:
    docker:
      - image: circleci/node:lts # this will almost always be the case unless the project needs a custom docker file
    steps:
      - checkout # step in ci that gets code from GitHub
      - run:
          name: Run tests
          command: 'echo "I'll build these tests later!"'
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Webpack
          command: npm run build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: "npm install"
      - run: "npm run test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
